// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeFrRoCpsjb635ouYyH9_qzChcpeQ7HOw',
    appId: '1:43028051871:web:6dfaf437c2289d38f32faa',
    messagingSenderId: '43028051871',
    projectId: 'loio-customer',
    authDomain: 'loio-customer.firebaseapp.com',
    storageBucket: 'loio-customer.appspot.com',
    measurementId: 'G-T81TDDM15G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHEaY47C1iDzyOVOdAgCHIcriWNEl8HIA',
    appId: '1:43028051871:android:fcd3aae2edf42b22f32faa',
    messagingSenderId: '43028051871',
    projectId: 'loio-customer',
    storageBucket: 'loio-customer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyBP1QoqTv5ItuPJI6CHfSsg7uG-sWw8Q',
    appId: '1:43028051871:ios:d80f3a13bb9fdc33f32faa',
    messagingSenderId: '43028051871',
    projectId: 'loio-customer',
    storageBucket: 'loio-customer.appspot.com',
    iosBundleId: 'com.example.leftoverIsOverCustomer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeFrRoCpsjb635ouYyH9_qzChcpeQ7HOw',
    appId: '1:43028051871:web:6dfaf437c2289d38f32faa',
    messagingSenderId: '43028051871',
    projectId: 'loio-customer',
    authDomain: 'loio-customer.firebaseapp.com',
    storageBucket: 'loio-customer.appspot.com',
    measurementId: 'G-T81TDDM15G',
  );

}