spring:
  application:
    name: leftover-is-over-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      minimum-idle: 2
      maximum-pool-size: 5
      idle-timeout: 120000
      connection-timeout: 300000
      leak-detection-threshold: 300000
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
jwt:
  secret: ${SECRET_KEY}

springdoc:
  swagger-ui:
    path: /api
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
