// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDTdVsUKgg6wpmZnJXY2l6nKLtKCRWYYc',
    appId: '1:354614371003:web:4c9326cf917c73f22a3f9e',
    messagingSenderId: '354614371003',
    projectId: 'opensoftware-c8519',
    authDomain: 'opensoftware-c8519.firebaseapp.com',
    storageBucket: 'opensoftware-c8519.appspot.com',
    measurementId: 'G-7V4S407W0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGCTJNJ7zakwVYotZ7PDTWx535nk_3Pto',
    appId: '1:354614371003:android:ef0813189661a6832a3f9e',
    messagingSenderId: '354614371003',
    projectId: 'opensoftware-c8519',
    storageBucket: 'opensoftware-c8519.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA763GKZuG2fR-BSZG8pmgeW7tOxnK388A',
    appId: '1:354614371003:ios:4cf90a26ff15e9f82a3f9e',
    messagingSenderId: '354614371003',
    projectId: 'opensoftware-c8519',
    storageBucket: 'opensoftware-c8519.appspot.com',
    iosBundleId: 'com.example.leftoverIsOverOwner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA763GKZuG2fR-BSZG8pmgeW7tOxnK388A',
    appId: '1:354614371003:ios:4cf90a26ff15e9f82a3f9e',
    messagingSenderId: '354614371003',
    projectId: 'opensoftware-c8519',
    storageBucket: 'opensoftware-c8519.appspot.com',
    iosBundleId: 'com.example.leftoverIsOverOwner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDTdVsUKgg6wpmZnJXY2l6nKLtKCRWYYc',
    appId: '1:354614371003:web:45dcd8223f3914b82a3f9e',
    messagingSenderId: '354614371003',
    projectId: 'opensoftware-c8519',
    authDomain: 'opensoftware-c8519.firebaseapp.com',
    storageBucket: 'opensoftware-c8519.appspot.com',
    measurementId: 'G-KEN5CTGFK0',
  );
}
