// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2q4wcKj4UdAKwhLFgzqCph-jN1Uu1OrA',
    appId: '1:39756391312:web:21858fc23fa6cfe6cec915',
    messagingSenderId: '39756391312',
    projectId: 'loio-6310d',
    authDomain: 'loio-6310d.firebaseapp.com',
    storageBucket: 'loio-6310d.appspot.com',
    measurementId: 'G-13QPFVX670',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeiJUKd_3NMyCgRcuzIaUDH8LJfGIwJXo',
    appId: '1:39756391312:android:a4ca54513287a167cec915',
    messagingSenderId: '39756391312',
    projectId: 'loio-6310d',
    storageBucket: 'loio-6310d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD64ZVY9qxVyECKb90E3eNywz8FWafadFI',
    appId: '1:39756391312:ios:4ec53b9baf055b15cec915',
    messagingSenderId: '39756391312',
    projectId: 'loio-6310d',
    storageBucket: 'loio-6310d.appspot.com',
    iosBundleId: 'com.example.leftoverIsOverOwner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD64ZVY9qxVyECKb90E3eNywz8FWafadFI',
    appId: '1:39756391312:ios:4ec53b9baf055b15cec915',
    messagingSenderId: '39756391312',
    projectId: 'loio-6310d',
    storageBucket: 'loio-6310d.appspot.com',
    iosBundleId: 'com.example.leftoverIsOverOwner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2q4wcKj4UdAKwhLFgzqCph-jN1Uu1OrA',
    appId: '1:39756391312:web:1459fc2c18a35095cec915',
    messagingSenderId: '39756391312',
    projectId: 'loio-6310d',
    authDomain: 'loio-6310d.firebaseapp.com',
    storageBucket: 'loio-6310d.appspot.com',
    measurementId: 'G-4VJTBMVJSM',
  );

}