name: Build and deploy JAR app to Azure Web App - loio-server

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set executable permissions on Gradlew
        run: chmod +x gradlew
        working-directory: ${{github.workspace}}/backend

      - name: Build with Gradle
        run: ./gradlew build -x test
        working-directory: ${{github.workspace}}/backend

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: ${{github.workspace}}/backend/build/libs/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: java-app
          path: deploy/
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6F80F136ED7449C18F9A00505BDA5445 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A22975AB70E64F28A10CE76408457170 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_EF9B945544884DE9ADD132FEF1ABCAE1 }}

      - name: List files in deploy directory
        run: ls -la ./deploy/

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'loio-server'
          slot-name: 'production'
          package: './deploy/leftover-is-over-backend-0.0.1-SNAPSHOT.jar'
          
